trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - k8s/*

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build and push image
    jobs:
      - job: BuildAndPush
        displayName: Build and push image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "dockerhub"
              repository: "ferraroluc/flask-hello-world"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: |
                $(tag)
                latest

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: "vm"
              runOptions: "inline"
              inline: |
                docker pull ferraroluc/flask-hello-world:$(tag)
                if [ "$(docker ps -q -f name=flask-api)" ]; then
                  docker stop flask-api
                  docker rm flask-api
                fi
                docker run -d --name flask-api -p 5000:5000 ferraroluc/flask-hello-world:$(tag)
              readyTimeout: "20000"
