apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world
  labels:
    app: flask-hello-world
spec:
  type: ClusterIP
  selector:
    app: flask-hello-world
  ports:
    - port: 5000
      targetPort: 5000
